const languages = {
  english: {
    pomodoros: "Pomodoros Done",
    startButton: "Start",
    pauseButton: "Pause",
    stopButton: "Stop",
    continueButton: "Continue",
    resetButton: "Reset",
    settingsTitle: "Settings",
    timerSettings: "Timer Settings",
    focusDuration: "Focus Duration",
    shortBreakDuration: "Short Break Duration",
    longBreakDuration: "Long Break Duration (Every 4th Break)",
    language: "Language",
    saveButton: "Save",
    cancelButton: "Cancel",
  },
  ukrainian: {
    pomodoros: "Помодоро виконано",
    startButton: "Старт",
    pauseButton: "Пауза",
    stopButton: "Стоп",
    continueButton: "Далі",
    resetButton: "Скинути",
    settingsTitle: "Налаштування",
    timerSettingsTitle: "Налаштування таймера",
    focusDuration: "Тривалість фокус-сессії",
    shortBreakDuration: "Тривалість короткого відпочинку",
    longBreakDuration: "Тривалість довгого відпочинку (кожний 4-ий)",
    language: "Мова",
    saveButton: "Зберегти",
    cancelButton: "Скасувати",
  },
};
